# Generated by Django 5.1.4 on 2025-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('grade', models.CharField(choices=[('Grade', 'Grade'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], max_length=20)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
