# Generated by Django 5.1.5 on 2025-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Gender', 'select an option'), ('Male', 'Male'), ('Female', 'Female')], default=('Gender', 'select an option'), max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(choices=[('Grade', 'select an option'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=('Grade', 'select an option'), max_length=10),
        ),
    ]
