# Generated by Django 5.1.5 on 2025-01-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registration_gender_alter_registration_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
