# Generated by Django 5.1.5 on 2025-01-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('grade', models.CharField(choices=[('Grade', 'select an option'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=False, max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
