# Generated by Django 5.1.5 on 2025-01-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_subject',
            name='student',
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student', to='app.registration'),
        ),
    ]
