# Generated by Django 5.1.5 on 2025-01-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_student_subject_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
