# Generated by Django 5.1.5 on 2025-01-22 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_teacher_subject_subj_teach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ManyToManyField(related_name='roster', to='app.registration')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameing_teacher', to='app.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='student_subject',
        ),
    ]
