# Generated by Django 5.1.5 on 2025-01-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_class_leader_delete_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grade',
        ),
        migrations.AddField(
            model_name='subj_teach',
            name='grade',
            field=models.CharField(blank=True, choices=[('Grade', 'select an option'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=False, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='subj_teach',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subj_teach',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subj_teach',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teach', to='app.subject'),
        ),
        migrations.AddField(
            model_name='subj_teach',
            name='teacher',
            field=models.ManyToManyField(related_name='teach', to='app.teacher'),
        ),
    ]
