# Generated by Django 5.1.5 on 2025-01-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_teacher_grade_subj_teach_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('Grade', 'select an option'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=False, max_length=10, null=True)),
                ('student', models.ManyToManyField(related_name='student_subject', to='app.registration')),
                ('subject', models.ManyToManyField(related_name='subject_student', to='app.subject')),
            ],
        ),
    ]
