# Generated by Django 5.1.5 on 2025-01-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='middle_Name',
        ),
    ]
