# Generated by Django 5.1.5 on 2025-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_class_leader_created_at_class_leader_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_leader',
            name='grade',
            field=models.CharField(blank=True, choices=[('Grade', 'select an option'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='section',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
