# Generated by Django 5.1.5 on 2025-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_class_leader_grade_registration_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_leader',
            name='grade',
            field=models.CharField(blank=True, choices=[('Grade', 'select an section'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Gender', 'select an section'), ('Male', 'Male'), ('Female', 'Female')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(choices=[('Grade', 'select an section'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField(choices=[('A', 'section A'), ('B', 'section B'), ('C', 'section C')], default=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='grade',
            field=models.CharField(blank=True, choices=[('Grade', 'select an section'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subj_teach',
            name='grade',
            field=models.CharField(blank=True, choices=[('Grade', 'select an section'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=False, max_length=10, null=True),
        ),
    ]
