# Generated by Django 5.1.5 on 2025-01-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_class_leader_grade_alter_registration_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subj_teach',
            name='section',
            field=models.CharField(choices=[('A', 'section A'), ('B', 'section B'), ('C', 'section C')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='class_leader',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_9', 'Grade 9'), ('grade_10', 'Grade 10')], default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(choices=[('grade_9', 'Grade 9'), ('grade_10', 'Grade 10')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_9', 'Grade 9'), ('grade_10', 'Grade 10')], default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subj_teach',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_9', 'Grade 9'), ('grade_10', 'Grade 10')], default=False, max_length=10, null=True),
        ),
    ]
