# Generated by Django 5.1.5 on 2025-03-20 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_gender_alter_class_leader_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade9', models.IntegerField(blank=True, null=True)),
                ('grade10', models.IntegerField(blank=True, null=True)),
                ('grade11', models.IntegerField(blank=True, null=True)),
                ('grade12', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(blank=True, max_length=50, null=True)),
                ('B', models.CharField(blank=True, max_length=50, null=True)),
                ('C', models.CharField(blank=True, max_length=50, null=True)),
                ('D', models.CharField(blank=True, max_length=50, null=True)),
                ('E', models.CharField(blank=True, max_length=50, null=True)),
                ('F', models.CharField(blank=True, max_length=50, null=True)),
                ('G', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.AlterField(
            model_name='class_leader',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_grade', to='app.grade'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_grade', to='app.grade'),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='app.grade'),
        ),
        migrations.AlterField(
            model_name='subj_teach',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_grade', to='app.grade'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_section', to='app.section'),
        ),
        migrations.AlterField(
            model_name='subj_teach',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_section', to='app.section'),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_gender', to='app.gender'),
        ),
    ]
