# Generated by Django 5.1.5 on 2025-03-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_grade_section_remove_registration_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subj_teach',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='class_leader',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
