# Generated by Django 5.1.5 on 2025-03-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_student_subject_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subj_teach',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='class_leader',
            name='grade',
            field=models.CharField(choices=[('grade_9', '9'), ('grade_10', '10')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='grade',
            field=models.CharField(choices=[('grade_9', '9'), ('grade_10', '10')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='grade',
            field=models.CharField(choices=[('grade_9', '9'), ('grade_10', '10')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subj_teach',
            name='grade',
            field=models.CharField(choices=[('grade_9', '9'), ('grade_10', '10')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
