# Generated by Django 5.1.5 on 2025-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_subj_teach_section_alter_registration_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='class_leader',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_9', '9'), ('grade_10', '10')], default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(choices=[('grade_9', '9'), ('grade_10', '10')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_9', '9'), ('grade_10', '10')], default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subj_teach',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_9', '9'), ('grade_10', '10')], default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subj_teach',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
