# Generated by Django 5.1.5 on 2025-03-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_registration_gender_alter_class_leader_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=False, max_length=10),
        ),
    ]
