# Generated by Django 5.1.5 on 2025-03-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_gender_remove_registration_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
    ]
