# Generated by Django 5.1.5 on 2025-03-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_gender_remove_registration_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='gender',
            new_name='user_gender',
        ),
    ]
