# Generated by Django 5.1.5 on 2025-03-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_gender_registration_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user_gender',
        ),
    ]
