# Generated by Django 5.1.5 on 2025-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_registration_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=False, max_length=10),
        ),
    ]
