# Generated by Django 5.1.5 on 2025-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_gender_registration_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField(blank=True, null=True)),
                ('mid', models.IntegerField(blank=True, null=True)),
                ('participation', models.IntegerField(blank=True, null=True)),
                ('exercise', models.IntegerField(blank=True, null=True)),
                ('final', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
