# Generated by Django 5.1.5 on 2025-03-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_registration_user_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
