# Generated by Django 5.1.5 on 2025-05-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_newmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmark',
            name='fullname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app.registration'),
        ),
    ]
